name: CI

on:
  push:
    branches:
      - testing


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # Actualizado a v3
      with:
        fetch-depth: 0

    - name: Use Node.js
      uses: actions/setup-node@v3 # Actualizado a v3
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm run test
