name: Deploy Pabdro
on:
  push:
    branches:
      - 'release/**'
  schedule:
    - cron:  '45 19,0 * * 1' # UTC time
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy project
        run: echo "Levantando project"
